### ISSUE TITLE
Option to disable inquiry.

### ISSUE THREAD

**Issue by amilajack** [IanVS/eslint-nibble#26]
Linting is a common task run in tests. It would be nice if this project could detect the `NODE_ENV` and disable the prompt.

**Comment by amilajack** [comment]
Ideally, running `eslint-nibble` would fail when the linter finds errors (throw an Error code 1). This will make tests fail if the linter finds errors.

**Comment by pmcelhaney** [comment]
You can accomplish that by running eslint directly. Nibble is for when you have more errors than you can fix at once (linting legacy code) and you want to fix a little bit at a time.

**Comment by IanVS** [comment]
> You can accomplish that by running eslint directly.

Precisely.  @amilajack, this is really just a tool to get you started with ESLint.  As it says in the readme:

>try installing eslint-nibble in your project without --save-dev (as shown above), because this tool is intended only to get you up and running. Once you're happy with your rules and your code, install eslint itself with npm install eslint --save-dev and use that for all your ongoing linting.

**Comment by IanVS** [comment]
@amilajack feel free to jump in the [ESLint gitter chat](https://gitter.im/eslint/eslint) if you'd like help getting it set up for your project.  Or continue to use this issue to discuss.  But I'm going to close it for now because I don't think that running `eslint-nibble` within tests is within the scope of what this particular project aims to do.
