### ISSUE TITLE
Select multiple rules at a time?

### ISSUE THREAD

**Issue by ljharb** [IanVS/eslint-nibble#46]
I'd love a way to select multiple rules at a time, in particular so I can apply multiple whitespace rules all at once (generating the initial report takes a lot of time)

**Comment by IanVS** [comment]
Would it meet your needs if multiple rules could be passed on the cli (https://github.com/IanVS/eslint-nibble/issues/47)?

**Comment by ljharb** [comment]
Yes; but at that point it’d seem inconsistent to only allow one via the UI.

**Comment by IanVS** [comment]
I took another look, and it seems it might be possible with inquirer using a `checkbox` type
(https://github.com/SBoudrias/Inquirer.js#checkbox---type-checkbox).  If I get some time I'll try it out.

**Comment by IanVS** [comment]
Subsequent lint runs are a lot faster now with `--cache`, and I'm reluctant to use the checkbox option because it's more cumbersome to use.  The faster speed, together with the new `--rule` flag, _should_ be enough to meet your needs here.  If you'd like to try, it's available as `eslint-nibble@next`.  If you still need multiple rules, I can add a `--multi` flag, but I wouldn't want it to be the default.  Thoughts?

**Comment by ljharb** [comment]
Since I’m intending to fix all whitespace-related rules at once, it’d be great to have a multi flag - it needn’t be the default.

**Comment by slorber** [comment]
hey @IanVS thanks for this tool

I'd like to nibble only error rules and exclude warning rules, is that possible instead of mananing myself a hardcoded list in the cli cmd?

**Comment by IanVS** [comment]
Hi @slorber, great idea.  I've added a `--no-warnings` option, available in version `5.1.0`.

**Comment by slorber** [comment]
great thanks ;)

**Comment by kaatt** [comment]
I second this. Would save a lot of time if I could select multiple rules using the CLI (instead of passing flags).

**Comment by IanVS** [comment]
Better late than never? https://github.com/IanVS/eslint-nibble/releases/tag/v6.0.0
