### ISSUE TITLE
Only pass previously errored filenames when fixing

### ISSUE THREAD

**Issue by ljharb** [IanVS/eslint-nibble#48]
If I run eslint-nibble on 10,000 files (which takes, say, 5 minutes to process), and the rule I select only has an error in 200 files, I would expect eslint to take, say, 1 minute to run on only those 200 files, instead of the full 5 minutes to run on all 10K files.

This could be achieved by minimizing what file paths are passed to the `eslint --fix` run - via a custom ignore file that ignores the non-errored files; or via a glob path that minimizes which un-errored files are processed the second time around.

**Comment by IanVS** [comment]
Rather than try to generate a custom ignore file, I think that https://github.com/IanVS/eslint-nibble/pull/42 would help speed things up, because only failing files will be re-linted.  It's not a perfect solution, because _all_ failing files will be re-linted, not just the ones that are failing for the particular rule(s) selected.  I'll work on getting that merged/released, and then maybe you can let me know if it's good enough?

**Comment by ljharb** [comment]
That seems like a great first step :-)

**Comment by IanVS** [comment]
I believe that https://github.com/IanVS/eslint-nibble/pull/42 combined with the [recent improvements](https://eslint.org/blog/2018/07/eslint-v5.2.0-released#highlights) in eslint caching should be enough to close this issue.
