### ISSUE TITLE
Respect .eslintignore file

### ISSUE THREAD

**Issue by Alex-Sokolov** [IanVS/eslint-nibble#54]
Some files needed to be ignored by eslint-nibble (which already ignored eslint via .eslintignore), but now there are no ways to do it

**Comment by IanVS** [comment]
It _should_ already be respecting the `.eslintignore` file, because under the hood eslint is still being run on the files.  I'll do some investigating to dobule-check that, but can you confirm that you have a single `.eslintignore` file located at your project root?  And are you running `eslint-nibble` from your project root as well?  Any details you can share would be helpful.

**Comment by Alex-Sokolov** [comment]
Sorry! I am confused between two our projects, which one have eslintignore, and one which not :)
